service: serverless-for-create-pdf
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createPDF:
    handler: handler.createPDF
    events:
      - schedule:
          name: create-pdf-warmer
          rate: rate(4 minutes)
          enabled: true
          input:
            isWarmer: true
      - httpApi:
          path: /create-pdf
          method: post
