service: serverless-for-create-pdf
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  region: "ap-northeast-2"
  timeout: 29
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createPDF:
    handler: handler.createPDFHandler
    events:
      - schedule:
          name: create-pdf-warmer
          rate: rate(10 minutes)
          enabled: true
          input:
            isWarmer: true
      - httpApi:
          path: /create-pdf
          method: post

package:
  exclude:
    - undefined/**
