service: serverless-for-create-pdf
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  runtimeManagement:
    mode: manual
    arn: arn:aws:lambda:ap-northeast-2::runtime:b475b23763329123d9e6f79f51886d0e1054f727f5b90ec945fcb2a3ec09afdd
  memorySize: 1024
  region: "ap-northeast-2"
  timeout: 29
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createPDF:
    handler: handler.createPDFHandler
    events:
      - schedule:
          name: create-pdf-warmer
          rate: rate(10 minutes)
          enabled: true
          input:
            isWarmer: true
      - httpApi:
          path: /create-pdf
          method: post
  createPDFWithUpload:
    handler: handler.createPDFWithUploadHandler
    events:
      - schedule:
          name: create-pdf-with-upload-warmer
          rate: rate(10 minutes)
          enabled: true
          input:
            isWarmer: true
      - httpApi:
          path: /create-pdf-with-upload
          method: post

package:
  exclude:
    - undefined/**
